-- HNBLUE V2.0 public source seed generated from second deep search.
-- Do not execute against the V1.0 hnblue demo schema.
-- Target schema checked against sql/schema/hnblue_v2_schema.sql.

INSERT INTO hainan_blue_carbon_core.t_data_source
(source_code, source_category, source_name, publisher, author_or_team, source_url, access_date, license_text, version_label, is_simulated, remark)
VALUES
('SRC_LIT_BAMEN_SOC_2022','LITERATURE','Spatial Variation of Soil Organic Carbon from Bamen Bay Mangrove in Southern China','MDPI Water','article authors','https://www.mdpi.com/2073-4441/14/20/3278','2026-05-25','CC BY on publisher page','2022',0,'Wenchang Bamen Bay SOC, area, coordinates and species context'),
('SRC_LIT_HI_GHG_2022','LITERATURE','Incorporating coastal blue carbon into subnational greenhouse gas inventories','Frontiers in Marine Science','article authors','https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2022.932984/full','2026-05-25','CC BY on publisher page','2022',0,'Hainan mangrove area, EF_AGB, EF_SOC, GHG inventory'),
('SRC_LIT_HI_GOV_2023','GOVERNMENT_DATA','Hainan blue carbon public information','Hainan Provincial Government','','https://en.hainan.gov.cn/hainan/zmgyshj/202307/3f612bd40e1941a080bf7abef3b71c69.shtml','2026-05-25','Government webpage, reuse restriction to be reviewed','2023-07',0,'37 mangrove species, 145 sediment cores, 363 vegetation plots, carbon density range'),
('SRC_RS_GMW_V3','PUBLIC_DATASET','Global Mangrove Watch 1996-2020 Version 3.0','Global Mangrove Watch / Zenodo','','https://zenodo.org/records/6894273','2026-05-25','Zenodo dataset license to be reviewed','v3.0',0,'25m mangrove extent product'),
('SRC_RS_GMW_PLATFORM','PUBLIC_DATASET','Global Mangrove Watch platform','Global Mangrove Watch','','https://globalmangrovewatch.org/','2026-05-25','Platform terms to be reviewed','ongoing',0,'Mangrove monitoring portal'),
('SRC_RS_LANDSAT_MANGROVE_GEE','PUBLIC_DATASET','Global Mangrove Forests Distribution 2000','Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_MANGROVE_FORESTS','2026-05-25','GEE data catalog terms','2000',0,'Global mangrove baseline'),
('SRC_RS_S2_GEE','PUBLIC_DATASET','Sentinel-2 MSI Level-2A SR Harmonized','ESA Copernicus / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED','2026-05-25','Copernicus and GEE terms','2017-present',0,'10m optical data'),
('SRC_RS_L8_C2_GEE','PUBLIC_DATASET','Landsat 8 Collection 2 Level 2','USGS / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_L2','2026-05-25','USGS open data terms','2013-present',0,'30m optical data'),
('SRC_RS_L5_C2_GEE','PUBLIC_DATASET','Landsat 5 Collection 2 Level 2','USGS / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LT05_C02_T1_L2','2026-05-25','USGS open data terms','1984-2012',0,'30m optical data'),
('SRC_RS_L7_C2_GEE','PUBLIC_DATASET','Landsat 7 Collection 2 Level 2','USGS / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LE07_C02_T1_L2','2026-05-25','USGS open data terms','1999-present',0,'30m optical data'),
('SRC_RS_MOD17_GEE','PUBLIC_DATASET','MODIS MOD17A3HGF GPP NPP','NASA LP DAAC / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD17A3HGF','2026-05-25','NASA LP DAAC terms','061',0,'GPP/NPP proxy product'),
('SRC_RS_MOD13Q1_GEE','PUBLIC_DATASET','MODIS MOD13Q1 vegetation indices','NASA / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD13Q1','2026-05-25','NASA terms','061',0,'250m NDVI/EVI'),
('SRC_RS_MYD13Q1_GEE','PUBLIC_DATASET','MODIS MYD13Q1 vegetation indices','NASA / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MYD13Q1','2026-05-25','NASA terms','061',0,'250m NDVI/EVI'),
('SRC_RS_MCD12Q1_GEE','PUBLIC_DATASET','MODIS MCD12Q1 land cover','NASA / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MCD12Q1','2026-05-25','NASA terms','061',0,'500m land cover'),
('SRC_RS_JRC_GSW_GEE','PUBLIC_DATASET','JRC Global Surface Water','European Commission JRC / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/JRC_GSW1_4_GlobalSurfaceWater','2026-05-25','JRC terms','1.4',0,'30m surface water'),
('SRC_RS_SRTM_GEE','PUBLIC_DATASET','NASA SRTM Digital Elevation 30m','NASA / USGS / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/USGS_SRTMGL1_003','2026-05-25','NASA/USGS terms','003',0,'DEM'),
('SRC_RS_COPDEM_GEE','PUBLIC_DATASET','Copernicus DEM GLO-30','Copernicus / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_DEM_GLO30','2026-05-25','Copernicus terms','GLO-30',0,'DEM'),
('SRC_RS_GEDI_L2A_GEE','PUBLIC_DATASET','GEDI L2A vector canopy top height','NASA GEDI / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LARSE_GEDI_GEDI02_A_002','2026-05-25','NASA terms','002',0,'Canopy height footprints'),
('SRC_RS_GEDI_L4A_GEE','PUBLIC_DATASET','GEDI L4A biomass density','NASA GEDI / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/LARSE_GEDI_GEDI04_A_002','2026-05-25','NASA terms','002',0,'AGBD footprints'),
('SRC_RS_CHIRPS_GEE','PUBLIC_DATASET','CHIRPS daily precipitation','UCSB CHG / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/UCSB-CHG_CHIRPS_DAILY','2026-05-25','Data provider terms','daily',0,'Precipitation covariate'),
('SRC_RS_ERA5_GEE','PUBLIC_DATASET','ERA5-Land daily aggregated','ECMWF / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_DAILY_AGGR','2026-05-25','ECMWF terms','daily',0,'Climate and evapotranspiration covariates'),
('SRC_RS_TERRACLIMATE_GEE','PUBLIC_DATASET','TerraClimate monthly climate','University of Idaho / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_TERRACLIMATE','2026-05-25','Dataset terms to be reviewed','monthly',0,'Climate variables'),
('SRC_RS_ESAWC_GEE','PUBLIC_DATASET','ESA WorldCover v200','ESA / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/ESA_WorldCover_v200','2026-05-25','ESA terms','2021',0,'10m land cover'),
('SRC_RS_DYNAMICWORLD_GEE','PUBLIC_DATASET','Dynamic World V1','Google / WRI / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_DYNAMICWORLD_V1','2026-05-25','Dataset terms to be reviewed','v1',0,'10m land cover probabilities'),
('SRC_RS_NASADEM_GEE','PUBLIC_DATASET','NASADEM HGT','NASA / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/NASA_NASADEM_HGT_001','2026-05-25','NASA terms','001',0,'DEM'),
('SRC_RS_WORLDCLIM_GEE','PUBLIC_DATASET','WorldClim BIO variables','WorldClim / Google Earth Engine','','https://developers.google.com/earth-engine/datasets/catalog/WORLDCLIM_V1_BIO','2026-05-25','WorldClim terms','v1',0,'Bioclim variables'),
('SRC_METHOD_IPCC_2013','PUBLIC_DATASET','2013 Supplement to the 2006 IPCC Guidelines for Wetlands','IPCC','','https://www.ipcc-nggip.iges.or.jp/public/wetlands/','2026-05-25','IPCC terms','2013',0,'Wetlands GHG methodology'),
('SRC_METHOD_IPCC_2006','PUBLIC_DATASET','2006 IPCC Guidelines for National GHG Inventories','IPCC','','https://www.ipcc-nggip.iges.or.jp/public/2006gl/','2026-05-25','IPCC terms','2006',0,'Inventory framework'),
('SRC_METHOD_BCI','PUBLIC_DATASET','Coastal Blue Carbon Methods Manual','Blue Carbon Initiative','Howard et al.','https://www.thebluecarboninitiative.org/manual','2026-05-25','Manual terms to be reviewed','2014',0,'Field methods'),
('SRC_METHOD_VERRA_VM0033','PUBLIC_DATASET','VM0033 Methodology for Tidal Wetland and Seagrass Restoration','Verra','','https://verra.org/methodologies/vm0033-methodology-for-tidal-wetland-and-seagrass-restoration-v2-1/','2026-05-25','Verra terms','v2.1',0,'Blue carbon project methodology'),
('SRC_ALLO_KOMIYAMA_2005','LITERATURE','Common allometric equations for estimating the tree weight of mangroves','Journal of Tropical Ecology / Springer','Komiyama et al.','https://link.springer.com/article/10.1007/s11284-005-0088-4','2026-05-25','Publisher terms','2005',0,'Common mangrove allometric equations'),
('SRC_ALLO_BAAD','PUBLIC_DATASET','BAAD Biomass And Allometry Database','BAAD authors / GitHub','','https://github.com/dfalster/baad','2026-05-25','Repository license to be reviewed','current',0,'Model reference data'),
('SRC_ALLO_TALLO','PUBLIC_DATASET','Tallo global tree allometry database','Zenodo / authors','','https://zenodo.org/','2026-05-25','Specific DOI to be reviewed','various',0,'Crown and height reference'),
('SRC_PLATFORM_ORNL_DAAC','PUBLIC_DATASET','NASA ORNL DAAC','NASA ORNL DAAC','','https://daac.ornl.gov/','2026-05-25','DAAC terms','ongoing',0,'Ecological data search portal'),
('SRC_PLATFORM_LP_DAAC','PUBLIC_DATASET','NASA LP DAAC','NASA LP DAAC','','https://lpdaac.usgs.gov/','2026-05-25','LP DAAC terms','ongoing',0,'MODIS and land products'),
('SRC_PLATFORM_COPERNICUS_BROWSER','PUBLIC_DATASET','Copernicus Browser','ESA Copernicus','','https://browser.dataspace.copernicus.eu/','2026-05-25','Copernicus terms','ongoing',0,'Sentinel data portal'),
('SRC_PLATFORM_USGS_EE','PUBLIC_DATASET','USGS EarthExplorer','USGS','','https://earthexplorer.usgs.gov/','2026-05-25','USGS terms','ongoing',0,'Landsat and DEM portal'),
('SRC_USGS_LANDSAT_C2','PUBLIC_DATASET','Landsat Collection 2 Level-2 Science Products','USGS / NASA','','https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products','2026-05-25','USGS terms','Collection 2',0,'Official Landsat C2 L2 documentation'),
('SRC_LIT_HI_JORAE_2022','LITERATURE','Assessment of Mangrove Carbon Stock in Hainan Island','Journal of Resources and Ecology','article authors','https://www.jorae.cn/CN/10.5814/j.issn.1674-764x.2022.03.010','2026-05-25','Publisher terms','2022',0,'Abstract page; full numeric table unresolved'),
('SRC_GOV_HI_RESTORATION_2025','GOVERNMENT_DATA','Hainan mangrove protection and restoration project information','Hainan Provincial Government','','https://en.hainan.gov.cn/hainan/zdjsxm/202510/d9dd6ae78ac74071aa8995d56dd633e7.shtml','2026-05-25','Government webpage terms to be reviewed','2025',0,'Restoration project context')
ON DUPLICATE KEY UPDATE
source_name=VALUES(source_name),
source_url=VALUES(source_url),
access_date=VALUES(access_date),
remark=VALUES(remark);
