-- HNBLUE V2.0 Phase 3 core minimal import preview
-- Contains only hainan_blue_carbon_core.t_data_source and hainan_blue_carbon_core.t_region.
-- 本轮脚本未连接 MySQL，未执行导入。执行前必须先运行 hnblue_v2_phase3_preflight_check.sql。
-- satellite and intl fact tables are intentionally deferred.
SET NAMES utf8mb4;

-- Optional manual transaction wrapper:
-- START TRANSACTION;

-- 1. Minimal source dictionary import
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_LIT_BAMEN_SOC_2022', 'LITERATURE', 'Spatial Variation of Soil Organic Carbon from Bamen Bay Mangrove in Southern China', 'https://www.mdpi.com/2073-4441/14/20/3278', 'Spatial Variation of Soil Organic Carbon from Bamen Bay Mangrove in Southern China', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_LIT_FORESTS_HI_MANGROVE_RS_2023', 'DERIVED_PRODUCT', 'Using Medium-Resolution Remote Sensing Satellite Images to Evaluate Recent Changes and Future Development Trends of Mangrove Forests on Hainan Island, China', 'https://www.mdpi.com/1999-4907/14/11/2217', 'Using Medium-Resolution Remote Sensing Satellite Images to Evaluate Recent Changes and Future Development Trends of Mangrove Forests on Hainan Island, China', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_LIT_FRONTIERS_HI_LULC_INVEST_2024', 'MODEL_OUTPUT', 'The impact of land use change on carbon storage and multi-scenario prediction in Hainan Island using InVEST and CA-Markov models', 'https://www.frontiersin.org/journals/forests-and-global-change/articles/10.3389/ffgc.2024.1349057/full', 'The impact of land use change on carbon storage and multi-scenario prediction in Hainan Island using InVEST and CA-Markov models', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_LIT_HI_GHG_2022', 'LITERATURE', 'Incorporating coastal blue carbon into subnational greenhouse gas inventories', 'https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2022.932984/full', 'Incorporating coastal blue carbon into subnational greenhouse gas inventories', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_ALLO_KOMIYAMA_2005', 'LITERATURE', 'Common allometric equations for estimating the tree weight of mangroves', 'https://link.springer.com/article/10.1007/s11284-005-0088-4', 'Common allometric equations for estimating the tree weight of mangroves', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_BAAD_BIOMASS_AND_ALLOMETRY_DATABASE', 'PUBLIC_DATASET', 'BAAD Biomass And Allometry Database', 'https://github.com/dfalster/baad', 'BAAD Biomass And Allometry Database', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_GOV_HI_BLUE_CARBON_2023', 'GOVERNMENT_DATA', '海南发挥环境资源优势与自贸港政策优势，积极推动蓝碳事业发展', 'https://en.hainan.gov.cn/hainan/zmgyshj/202307/3f612bd40e1941a080bf7abef3b71c69.shtml', '海南发挥环境资源优势与自贸港政策优势，积极推动蓝碳事业发展', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_IPCC_WETLANDS_SUPPLEMENT', 'LITERATURE', 'IPCC Wetlands Supplement', 'https://www.ipcc-nggip.iges.or.jp/public/wetlands/', 'IPCC Wetlands Supplement', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_data_source (source_code, source_category, source_name, source_url, citation_text, version_label, is_simulated, remark) VALUES ('SRC_TALLO_GLOBAL_TREE_ALLOMETRY_DATABASE', 'PUBLIC_DATASET', 'Tallo global tree allometry database', 'https://zenodo.org/', 'Tallo global tree allometry database', 'HNBLUE V2.0 public normalized package', 0, 'Normalized source summary for frontend filter and V2.0 ingest mapping.');

-- 2. Minimal region dictionary import
-- parent_region_id is resolved by parent region_code. Rows with blank parent_region_code use NULL.
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_GLOBAL', NULL, '全球', 'OTHER', '海南省', NULL, NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI', NULL, '海南省', 'PROVINCE', '海南省', NULL, NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_DONGFANG', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-东方', 'SITE_AREA', '海南省', NULL, '东方', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_DONGZHAIGANG', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-东寨港', 'SITE_AREA', '海南省', NULL, '东寨港', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_GUANNAN', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-冠南', 'SITE_AREA', '海南省', NULL, '冠南', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_HUACHANGWAN', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-花场湾', 'SITE_AREA', '海南省', NULL, '花场湾', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_HUIWEN', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-会文', 'SITE_AREA', '海南省', NULL, '会文', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_ISLAND', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛', 'PROVINCE', '海南省', NULL, NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_MANIAOGANG', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-马袅港', 'SITE_AREA', '海南省', NULL, '马袅港', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_PUQIAN', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-铺前', 'SITE_AREA', '海南省', NULL, '铺前', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_XINYINGGANG', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-新英港', 'SITE_AREA', '海南省', NULL, '新英港', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_HI_YANGPUGANG', (SELECT region_id FROM (SELECT region_id FROM hainan_blue_carbon_core.t_region WHERE region_code='REG_HI' LIMIT 1) AS parent_region_lookup), '海南岛-洋浦港', 'SITE_AREA', '海南省', NULL, '洋浦港', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_WENCHANG', NULL, '文昌市', 'CITY', '海南省', '文昌市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_WENCHANG_BAMEN_BAY', NULL, '文昌八门湾自然保护区', 'PROTECTED_AREA', '海南省', '文昌市', '文昌八门湾自然保护区', 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_万宁市', NULL, '万宁市', 'OTHER', '海南省', '万宁市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_三亚市', NULL, '三亚市', 'OTHER', '海南省', '三亚市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_东方市', NULL, '东方市', 'OTHER', '海南省', '东方市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_临高县', NULL, '临高县', 'OTHER', '海南省', '临高县', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_乐东县', NULL, '乐东县', 'OTHER', '海南省', '乐东县', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_儋州市', NULL, '儋州市', 'OTHER', '海南省', '儋州市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_昌江县', NULL, '昌江县', 'OTHER', '海南省', '昌江县', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_海口市', NULL, '海口市', 'OTHER', '海南省', '海口市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_澄迈县', NULL, '澄迈县', 'OTHER', '海南省', '澄迈县', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_琼海市', NULL, '琼海市', 'OTHER', '海南省', '琼海市', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');
INSERT IGNORE INTO hainan_blue_carbon_core.t_region (region_code, parent_region_id, region_name, region_level, province, city, county, ecosystem_type, data_scope, remark) VALUES ('REG_陵水县', NULL, '陵水县', 'OTHER', '海南省', '陵水县', NULL, 'MANGROVE', 'PUBLIC', 'Display dictionary generated from normalized public results.');

-- 3. Post-import count checks
SELECT COUNT(*) AS matched_public_sources
FROM hainan_blue_carbon_core.t_data_source
WHERE source_code IN ('SRC_LIT_BAMEN_SOC_2022', 'SRC_LIT_FORESTS_HI_MANGROVE_RS_2023', 'SRC_LIT_FRONTIERS_HI_LULC_INVEST_2024', 'SRC_LIT_HI_GHG_2022', 'SRC_ALLO_KOMIYAMA_2005', 'SRC_BAAD_BIOMASS_AND_ALLOMETRY_DATABASE', 'SRC_GOV_HI_BLUE_CARBON_2023', 'SRC_IPCC_WETLANDS_SUPPLEMENT', 'SRC_TALLO_GLOBAL_TREE_ALLOMETRY_DATABASE');

SELECT COUNT(*) AS matched_public_regions
FROM hainan_blue_carbon_core.t_region
WHERE region_code IN ('REG_GLOBAL', 'REG_HI', 'REG_HI_DONGFANG', 'REG_HI_DONGZHAIGANG', 'REG_HI_GUANNAN', 'REG_HI_HUACHANGWAN', 'REG_HI_HUIWEN', 'REG_HI_ISLAND', 'REG_HI_MANIAOGANG', 'REG_HI_PUQIAN', 'REG_HI_XINYINGGANG', 'REG_HI_YANGPUGANG', 'REG_WENCHANG', 'REG_WENCHANG_BAMEN_BAY', 'REG_万宁市', 'REG_三亚市', 'REG_东方市', 'REG_临高县', 'REG_乐东县', 'REG_儋州市', 'REG_昌江县', 'REG_海口市', 'REG_澄迈县', 'REG_琼海市', 'REG_陵水县');

-- 4. Manual rollback / cleanup SQL. Review FK dependencies before executing.
-- DELETE FROM hainan_blue_carbon_core.t_region
-- WHERE region_code IN ('REG_GLOBAL', 'REG_HI', 'REG_HI_DONGFANG', 'REG_HI_DONGZHAIGANG', 'REG_HI_GUANNAN', 'REG_HI_HUACHANGWAN', 'REG_HI_HUIWEN', 'REG_HI_ISLAND', 'REG_HI_MANIAOGANG', 'REG_HI_PUQIAN', 'REG_HI_XINYINGGANG', 'REG_HI_YANGPUGANG', 'REG_WENCHANG', 'REG_WENCHANG_BAMEN_BAY', 'REG_万宁市', 'REG_三亚市', 'REG_东方市', 'REG_临高县', 'REG_乐东县', 'REG_儋州市', 'REG_昌江县', 'REG_海口市', 'REG_澄迈县', 'REG_琼海市', 'REG_陵水县');
-- DELETE FROM hainan_blue_carbon_core.t_data_source
-- WHERE source_code IN ('SRC_LIT_BAMEN_SOC_2022', 'SRC_LIT_FORESTS_HI_MANGROVE_RS_2023', 'SRC_LIT_FRONTIERS_HI_LULC_INVEST_2024', 'SRC_LIT_HI_GHG_2022', 'SRC_ALLO_KOMIYAMA_2005', 'SRC_BAAD_BIOMASS_AND_ALLOMETRY_DATABASE', 'SRC_GOV_HI_BLUE_CARBON_2023', 'SRC_IPCC_WETLANDS_SUPPLEMENT', 'SRC_TALLO_GLOBAL_TREE_ALLOMETRY_DATABASE');

-- Choose exactly one after manual execution inside a transaction:
-- COMMIT;
-- ROLLBACK;
